
library:
  # Selfexplained folders
  BOOK_STOCK: "/books/stock" # Book stock
  # NEW_ACQUISITIONS: "/books/new" # Uncomment the line to have separate folder for new acquired books
  TRASH: "/books/trash" # Error and duplicate files and archives wil be moved to this folder 

language:
  # Russian, can be changed to "en" for English interface. 
  DEFAULT: "ru"  

database:
  DSN: "flibgo:flibgo@tcp(db:3306)/flibgo?charset=utf8"
  INIT_SCRIPT: "config/mysql_db_init.sql"
  DROP_SCRIPT: "config/mysql_db_drop.sql"
  # New aqusitions processing period
  POLL_PERIOD: 30 
  # Maximum simultaneous new aquisitios processing threads
  MAX_SCAN_THREADS: 3
  # Process only this languages puplications
  ACCEPTED_LANGS: "en,ru"

genres:
  TREE_FILE: "config/genres.xml"
  # Alternative genres can be used (Russian only, sorry) 
  # TREE_FILE: "config/alt_genres.xml"
  
logs:
  # Logs are here
  OPDS: "logs/opds.log"
  SCAN: "logs/scan.log"
  LEVEL: "I" # E - error, I - info, D - debug in ascending verbosity level order

opds:
  # OPDS-server port
  PORT: 8085
  # OPDS feeds entries page size
  PAGE_SIZE: 30

